# 텐서 생성 및 변환

In [1]:
import torch

In [3]:
print(torch.tensor([[1,2],[3,4]]))
#print(torch.tensor([[1,2],[3,4]], device='cuda:0")) #쿠다 설치안되면 오류 발생
                 

tensor([[1, 2],
        [3, 4]])


### 텐서를 ndarray로 변환

In [4]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())
# print(temp.to("cpu").numpy())    # GPU상의 텐서를 CPU의 텐서로 변환 후 ndarray로 변환

[[1 2]
 [3 4]]


### 텐서의 인덱스 조작

In [13]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])    #파이토치로 1차원 벡터 생성
print(temp[0])
print('----------------')
print(temp[2:5], temp[4:-1])

tensor(1.)
----------------
tensor([3., 4., 5.]) tensor([5., 6.])


## 텐서 연산 및 차원조작
### 사칙연산

In [14]:
v = torch.tensor([1,2,3])
w = torch.tensor([4,5,6])
print(w-v)

tensor([3, 3, 3])


### 차원조작

In [15]:
print(temp)

tensor([1., 2., 3., 4., 5., 6., 7.])


In [18]:
temp = torch.tensor([[1,2],[3,4]])

In [19]:
print(temp.shape)

torch.Size([2, 2])


In [20]:
print(temp.view(4,1))   # 2X2행렬을 4X1 행렬로

tensor([[1],
        [2],
        [3],
        [4]])


In [21]:
print(temp.view(-1))  #2X2행렬을 1차원 벡터로 변형

tensor([1, 2, 3, 4])


In [22]:
print(temp.view(1,-1))  #-1은 (1,?)와 같은 의미, 다른 차원의 값에 의해 ?가 결정. temp의 원소개수가 2x2=4 를 유지하기 위해 (1,4)로 결정됨

tensor([[1, 2, 3, 4]])


In [24]:
print(temp.view(-1,1))  #위와 동일 즉,(4,1)

tensor([[1],
        [2],
        [3],
        [4]])


# 테이터 준비

In [25]:
# 필요한 라이브러리 설치
# pip install pandas

In [29]:
# 라이브러리 호출
import pandas as pd
import torch
data = pd.read_csv('../class2.csv')    

x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()       # CSV파일의 x칼럼의 값을 넘파이 배열로 받아 Tensor(dtype)으로 바꿈
y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()       # CSV파일의 y칼럼의 값을 넘파이 배열로 받아 Tessor(dtype)으로 바꿈

# 위 코드는 예제로 실행안됨

FileNotFoundError: [Errno 2] No such file or directory: '../class2.csv'